### ISSUE TITLE
Propose approach to allow for camera moving and zooming in/out

### ISSUE THREAD

**Issue by guiltygyoza** [topology-gg/shoshin-tooling#22]
Without camera movement and zooming, characters would move off the display window (`Simulator` component). We need to zoom out as characters are further apart, and zoom in as they come closer; at all times both characters in the battle should be visible in the display window.

**Comment by zinkkrysty** [comment]
* What are the bounds of the scene? I think introducing some boundary will make this problem much smaller.
* Without a background of the simulation, the zoom in and out (and panning) will feel weird and unnatural. We should first introduce a background before we do any camera work.
* What if both characters go into one direction, off-screen, how should the camera follow them?
* I think there will be a lot of adjustment and math needed to do to make the camera movement feel natural and not make the viewer feel motion sick. I would suggest to save this feature to a later stage of the project - and perhaps involve a specialist in game animations and camera movements

**Comment by guiltygyoza** [comment]
1 - I was thinking the scene can be boundless. Perhaps that's not going to work.
2 - Agreed. I think the background used here https://twitter.com/guiltygyoza/status/1539696376870838278?s=20&t=m3R-2teLqR2UCXCN53jP7w would work.
3 & 4 - Agreed. Let's start with constant zoom, no camera, and placing bounds at both edges of the screen.
